baseURL = "http://example.com/"
languageCode = "en-us"
title = "SIPPS (2021)"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Camille Gasser"
    description = "Summer Internship Program in Psychological Science"
    descriptionSub = "hosted by Columbia University's Psychology Department"
    githubUsername = "#"
    accent = "#63AAB5"
    showBorder = true
    backgroundColor = "white"
    font = "Lato" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/schedule/"
    name = "Schedule"
    weight = 3

[[menu.main]]
    url = "/workshops/"
    name = "Workshops"
    weight = 4

[[menu.main]]
    url = "/team/"
    name = "Meet the Team"
    weight = 5
    
[[menu.main]]
    url = "/resources/"
    name = "Resources"
    weight = 6

[[menu.main]]
    url = "/sipps2020/"
    name = "SIPPS 2020"
    weight = 7

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "fab fa-stack-overflow"
    weight = 5
    
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
