---
title: "About the SIPPS Program"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h3>→ What is SIPPS?</h3>

<p style="margin-left:8%;">SIPPS is a 10-week summer program hosted within Columbia University’s Psychology department that aims to provide Columbia undergraduate and post-bac students with an immersive and practical introduction to psychological research. The SIPPS curriculum comprises two main components: (1) multiple weekly workshops, which involve hands-on training in practical research methods and tools (e.g., statistical analysis and coding, experimental design, and literature reviews); and (2) a mentored research experience, under the supervision of a graduate student or postdoctoral mentor. SIPPS culminates in an end-of-summer mini-conference, during which mentees present their research to each other and to other members of the department. </p>

<p style="margin-left:8%;">The following points delineate the motivation and goals for the program:</p>

<ul><ul><ul>
<li>Increase access to research opportunities for Columbia students who have little to no prior research experience
<li>Provide professional development and one-on-one mentoring opportunities in a safe, supportive environment
<li>Equip students with practical research skills
<li>Create student leadership opportunities
<li>Increase participation of individuals from diverse/historically underrepresented backgrounds. 
</ul></ul></ul>
</p>

<h3>→ Who are the SIPPS team?</h3>

<p style="margin-left:8%;">The SIPPS team is a group of graduate students, post-docs, research staff, and faculty advisors who are committed to increasing access to research opportunities for Columbia undergraduates and affiliates (e.g., research staff, psychology post-bacc program students) who have little to no prior research experience. Our research interests span a wide variety of topics including cognitive development, neuroscience, social interactions, perception, attention, memory, decision-making, personality psychology, and more.</p>

<h3>→ Who is SIPPS for?</h3>

<p style="margin-left:8%;">SIPPS is specifically intended for those with little to no experience conducting research in university settings. We recognize that obtaining a position within a psychology lab can be daunting, with many labs seeking applicants who already have considerable experience conducting research. We hope that SIPPS can provide a foundation of knowledge about how psychological research is conducted, how ideas are generated and shared, as well as what tools and methods are commonly employed — which will ultimately make our trainees better equipped for future research opportunities. Although the program is catered towards those who are interested in gaining experience in conducting psychological research, we also note that many of the skills taught through the weekly workshops are transferable to non-academic careers. That being said, the current program does not train students in clinical practice (e.g., psychiatry, therapy).</p>

<h3>→ What do we hope for SIPPS in the future?</h3>

<p style="margin-left:8%;">Going forward, we aim to make SIPPS a more equitable program that better serves individuals both within and outside Columbia University. One of our primary, ongoing goals is to secure funding for our program, which would allow us to offer financial support to SIPPS mentees throughout the summer (note that some of our students from prior years have been funded through various Columbia mechanisms, but we are currently looking for SIPPS-specific funding that would enable us to expand and supplement these mechanisms). This goal is critical to our mission to increase access to research opportunities for all students, but also, particularly those from backgrounds that are historically underrepresented in STEM, including those who identify as first-generation students, low-income students, and/or those with marginalized identities. We firmly believe that students should be paid for the work they do within the program, and recognize that not paying students acts as a barrier to increasing diversity and equity in research.
<br>
Second, as members of Columbia University, we recognize that we have access to resources that may not be more widely available across other institutions and the world. Thus, we hope to be able to make resources from our program (e.g., workshop materials, recordings, etc.) freely available on our website.</p>


<hr>
### SIPPS Testimonials (2021)
<br>
<blockquote>
<p style="font-size:1.1em">"Participating in SIPPS was a super insightful experience! I got to experience lab culture and methods in research. Spending my summer attending SIPPS workshops, pursuing independent project, and experiencing mentoring solidified my will to pursue academia. I learnt a lot about doing research and sticking through the entire process. <b>SIPPS has played a huge role in helping me narrow my interests down for graduate school.</b>"</p>
</blockquote>

<br>

<blockquote>
<p style="font-size:1.1em">"Best summer! SIPPS was genuinely so amazing. Though I live half way across the world, I never missed a single session! All the teachers were so amazing and helpful. I think this is a really great learning opportunity for international students. <b>The program introduced me to so many new skills and has also sparked a flare for scientific research!</b>"</p>
</blockquote>

<br>

<blockquote>
<p style="font-size:1.1em">"Not only did SIPPS equip me with the necessary skills to accomplish high quality research in psychological sciences, from literature reviews, open science practices, study administration and statistical coding, they gifted me with <b>opportunities to collaborate, make new friends, and jumpstart my academic career as a young researcher</b>. While SIPPS only lasted 10 weeks, I’ll be reaping the benefits for years to come. Thank you, SIPPS!"</p>
</blockquote>

<br>

<blockquote>
<p style="font-size:1.1em">"After completing SIPPS, <b>I consider myself not only a student, but a researcher.</b> While I'm still a beginner, this program introduced me to several research tools, built my skills in all components of the research cycle, and increased my self-confidence."</p>
</blockquote>

<br>

<blockquote>
<p style="font-size:1.1em">"<b>I really valued the close mentorship that I got through the SIPPS program.</b> My mentor met with me multiple times weekly and was extremely supportive in helping to guide me through my research project. She always pushed me to think deeper and taught me so much."</p>
</blockquote>

<br>

<blockquote>
<p style="font-size:1.1em">"This has been such an amazing program that has prepared me to be a great asset when working in a laboratory. The time that everyone dedicated to teach us about future careers, research skills, and strategies on how to perform better is time that I am so so thankful for! <b>This is a great program that everyone interested in psychology should take.</b>"</p>
</blockquote>

