---
title: "Apply"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div align="center"><h3>SIPPS 2023 applications are now open!</h3>
<br>
<h4>Follow [this link](https://forms.gle/pCCfusnVwtArzPFy9){target="_blank"} to apply. **Deadline:** <font color="#D6494A">April 14, 2023</font></h4>
<br>

<iframe src="/resources/SIPPS2023Flyer.pdf" width="80%" height="250px"></iframe></div>

<br>

<div style="padding: 15px; background-color: #f8f8f8">
<h4>Important Program Details</h4>
<ul>
<li>SIPPS 2023 will run from June 12 to August 18.
<br><br>
<li>This program intended for students with limited-to-no psychological research experience. There are no coursework or previous research requirements.
<br><br>
<li>SIPPS is <font color="#D6494A">**only open to current Columbia University undergraduate students.**</font>
<ul><li>This includes all Columbia schools (e.g., Columbia College, General Studies, Barnard College). 
<li>This does *not* include students who are graduating in spring 2023.</ul>
<br>
<li>SIPPS 2023 will take place <font color="#D6494A">**virtually**</font>.
<ul><li>If you are admitted to the program and happen to reside in NYC over the summer, you will be welcome to work with your mentor(s) in person — but this is not a requirement.
</ul>
<br>
<li>Unfortunately, we cannot offer funding to SIPPS mentees at this time.
</ul>
</div>

<br>

<div align="left"><h4>Questions or concerns?</h4></div>

<p style="margin-left: 35px;">
While the application period is open, we will be holding **weekly, informal info sessions (via zoom)** where you can drop in and ask any questions you have about SIPPS (e.g., the application process, program content, other personal concerns, etc.).</p>

<p style="margin-left: 35px;">These info sessions will take place from <u>3-4pm on Fridays throughout the application period</u> (3/17, 3/24, 3/31, 4/7, & 4/15) at [this zoom link](https://columbiauniversity.zoom.us/j/93329350605?pwd=anlDbkJkU1BXcjFDNHBIcWVER3k5QT09){target="_blank"}.</p>

<p style="margin-left: 35px;">Also feel free to reach out to [sippscupsych@gmail.com](mailto:sippscupsych@gmail.com){target="_blank"} at any time with your questions</p>
</div>
