---
title: "Diversity Statement"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The SIPPS team comprises a group of graduate students, post-docs, undergraduates, and faculty advisors who are committed to diversity and inclusion, in its [broadest sense](https://gsas.columbia.edu/our-intellectual-community/diversity-inclusion/statement-diversity-and-inclusion){target="_blank"}. We are scientists whose day-to-day research seeks to understand how people think, behave, and relate to one other and how differences in our experiences, both positive and adverse, affect our brain, relationships, and behavior. Our work encompasses and embraces the ideas of diversity and support. The success of SIPPS and our research in general depends on including and respecting people with diverse backgrounds, beliefs, and experiences. We have the privilege and responsibility of maintaining a program that promotes the well-being and excellence of all who participate in SIPPS and everyone we encounter. Our aim is to create a space where People of Color and/or from marginalized groups can work together and thrive from mentorship and resources to support students in all of their endeavors, both personally and in the world of research. 
