---
title: "Coding"
description: Learn how to use R to clean, analyze, and visualize your data.
weight: 1
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

See below for resources associated with the coding workshops from SIPPS 2023. For materials from other years and/or workshop series, follow [this link](/workshops). 

<hr>

### Week 1: Setting up your R environment
<br>

#### Before the workshop:
<p>
Before the workshop, please install R and RStudio on your computer. We have compiled this assortment of videos (not made by SIPPS instructors) that go over how to install these programs in Mac & PC, as well as introduce you to the RStudio environment.
<p>

Installation:
<ul>
<li>[Installing R & RStudio (Mac)](https://www.youtube.com/watch?v=LanBozXJjOk){target="_blank"}
<li>[Installing R & RStudio (PC)](https://www.youtube.com/watch?v=TFGYlKvQEQ4){target="_blank"}
<li>**Note:** Make sure to install the *latest* versions of R & RStudio, even if they don't match exactly what you see in the videos.
</ul>

<p>
Intro to RStudio:
<ul>
<li>[Introduction to RStudio](https://www.youtube.com/watch?v=glzNmxU1eU8){target="_blank"} (original video pulled from the [Columbia Psychology Scientific Computing](https://cu-psych-computing.github.io/cu-psych-comp-tutorial/){target="_blank"} workshop series)
<li>[Tour of the RStudio Interface](https://www.youtube.com/watch?v=XdgfhqNtje4){target="_blank"}
<li>**Note:** You don't necessarily need to watch both of these videos, just enough to familiarize yourself with the basics of what RStudio looks like and how to use it.
</ul>
<br>

#### During the workshop:
<p>
Create create a folder named `01_setup` on your computer and download these files <u>within that folder</u>:
<ul>
<li><a href="/workshop_files/2023/coding-01/shakes.csv" download>data file</a>
<li><a href="/workshop_files/2023/coding-01/01_lesson.Rmd" download>RMarkdown lesson file</a> 
<li><a href="/workshop_files/2023/coding-01/01_setup.Rproj" download>R Project file</a> 
</ul>
<br>

#### After the workshop:
<p>
Review <a href="/workshop_files/2023/coding-01/01_lessonKey.pdf" download>these slides</a> from the workshop. (We covered through slide 38, but feel free to review beyond that.)
<p>
Note that for this workshop, we only expect that you: (1) have successfully downloaded R & RStudio, (2) have some basic understanding of the different panels/panes of RStudio, how to open files, etc., and (3) know how to install and load packages (including `tidyverse`, `car`, `psych`, and `lme4`). We will get into the details of how to start actually writing R code next week.
<br><br>
<hr>

### Week 2: Programming fundamentals
<br>

#### Before the workshop:
<p>
Watch the pre-workshop video, and review the accompanying materials:
<ul>
<li>[Programming Fundamentals pre-workshop video](https://www.youtube.com/watch?v=iTLnZEOSYhE){target="_blank"}
<li>Create create a folder named `02_intro-programming` on your computer and download these files <u>within that folder</u>:
<ul>
<li><a href="/workshop_files/2023/coding-02/shakes.csv" download>data file</a>
<li><a href="/workshop_files/2023/coding-02/lesson.Rmd" download>RMarkdown lesson file</a>
<li><a href="/workshop_files/2023/coding-02/02_intro-programming.Rproj" download>R Project file</a>
</ul>
</ul>
<br>

#### During the workshop:
<p>
Download <a href="/workshop_files/2023/coding-02/challenge.Rmd" download>this file</a> for the synchronous workshop session & place it in the same `02_intro-programming` folder.
<br>
<br>

#### After the workshop:
<p>
Review the <a href="/workshop_files/2023/coding-02/challenge_key.Rmd" download>answer key</a> for challenge completed during the workshop. (We *strongly* recommend trying to work out answers yourself and/or talk to the instructor before consulting this answer key.)
<br><br>
<hr>

### Week 3: Data cleaning
<br>

#### Before the workshop:
<p>
Watch the pre-workshop video, and review the accompanying materials:
<ul>
<li>[Data cleaning pre-workshop video](https://youtu.be/gKI60TsHVsQ){target="_blank"}
<li>Create create a folder named `03_data-cleaning` on your computer and download these files <u>within that folder</u>:
<ul>
<li><a href="/workshop_files/2023/coding-03/Study1.csv" download>data file (csv)</a>
<li><a href="/workshop_files/2023/coding-03/Study1.rda" download>data file (rda)</a>
<li><a href="/workshop_files/2023/coding-03/lesson.Rmd" download>RMarkdown lesson file</a>
<li><a href="/workshop_files/2023/coding-03/03_data-cleaning.Rproj" download>R Project file</a>
</ul>
</ul>
<br>

#### During the workshop:
<p>
Download the following files for the synchronous workshop session and place them in the same `03_data-cleaning` folder.
<ul>
<li><a href="/workshop_files/2023/coding-03/superheroes.csv" download>data file (csv)</a>
<li><a href="/workshop_files/2023/coding-03/README_superheroes.txt" download>data file README (txt)</a>
<li><a href="/workshop_files/2023/coding-03/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>
<br>

#### After the workshop:
<p>
Review the <a href="/workshop_files/2023/coding-03/challenge_key.Rmd" download>answer key</a> for challenge completed during the workshop. (We *strongly* recommend trying to work out answers yourself and/or talk to the instructor before consulting this answer key.)
<br><br>
<hr>

### Week 4: No workshop session!
<br>
No workshop this week due to the Fourth of July.

<br><br>
<hr>

### Week 5: Data manipulation
<br>

#### Before the workshop:
<p>
Watch the pre-workshop video, and review the accompanying materials:
<ul>
<li>[Data manipulation pre-workshop video](https://youtu.be/VJDlwFjsKcI){target="_blank"}
<li>Create create a folder named `05_data-manipulation` on your computer and download these files <u>within that folder</u>:
<ul>
<li><a href="/workshop_files/2023/coding-05/Study1.csv" download>data file 1 (csv)</a>
<li><a href="/workshop_files/2023/coding-05/Study1_Followup.csv" download>data file 2 (csv)</a>
<li><a href="/workshop_files/2023/coding-05/lesson.Rmd" download>RMarkdown lesson file</a>
<li><a href="/workshop_files/2023/coding-05/05_data-manipulation.Rproj" download>R Project file</a>
<li>Note: In the pre-workshop video, the name of the project folder and R project file used start with `04` instead of `05`. Either numbering scheme is okay, just make sure your R project file has the same name as the folder you create to store these materials.
</ul>
</ul>
<br>

#### During the workshop:
<p>
Download the following files for the synchronous workshop session and place them in the same `05_data-manipulation` folder.
<ul>
<li><a href="/workshop_files/2023/coding-05/Study2_Subjects.csv" download>data file 1 (csv)</a>
<li><a href="/workshop_files/2023/coding-05/Study2_Trials.csv" download>data file 2 (csv)</a>
<li><a href="/workshop_files/2023/coding-05/README_Study2.txt" download>data file README (txt)</a>
<li><a href="/workshop_files/2023/coding-05/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>


<br>
<hr>

### Week 6: Correlations & basic visuals
<br>

#### Before the workshop:
<p>
Watch the pre-workshop video, and review the accompanying materials:
<ul>
<li>[Correlations & basic visuals pre-workshop video](https://youtu.be/WzLu_gYCiVk){target="_blank"}
<li>Create create a folder named `06_corr-viz` on your computer and download these files <u>within that folder</u>:
<ul>
<li><a href="/workshop_files/2023/coding-06/spotify_data.csv" download>data file (csv)</a>
<li><a href="/workshop_files/2023/coding-06/lesson.Rmd" download>RMarkdown lesson file</a>
<li><a href="/workshop_files/2023/coding-06/06_corr-viz.Rproj" download>R Project file</a>
</ul>
</ul>
<br><br>
<hr>

