---
title: "Coding (basic)"
description: Learn how to use R to clean, analyze, and visualize your data.
weight: 1
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On this page, you will find resources associated with each session in the basic-track coding workshop (<a href="https://columbiauniversity.zoom.us/j/93930272696?pwd=Y2s1U2VWY0pDR0ZQYTlxWC9mNzVmZz09" target="_blank">zoom link</a>, pw: sipps2021).
<br><br>
A few days before each session, please check this page to make sure you've downloaded any necessary files in advance (if needed). After each session, the page will be updated with links to the corresponding zoom recording, as well as any additional materials/answer keys/etc. that were referenced during the workshop.
<hr>

### Week 1: Setting up your R environment
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/DK-fdd1h5WcTIu-CBu_JHj31M46aZArRZGUejlqo3ssjL8fZ-ezEAjaBta65cHuQ.8CQ4myXSjViniuYN?startTime=1623182507000" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>download these files: <a href="/workshop_files/coding-basic-01/shakes.csv" download>data file</a>, <a href="/workshop_files/coding-basic-01/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/coding-basic-01/Coding_Lesson1.Rproj" download>R Project file</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-basic-01/lessonKey.Rmd" download>RMarkdown key</a>
</ul>

<hr>

### Week 2: Programming fundamentals
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/gcm3U1Vtyza9W3E3k7ApPW84_FJRsCtWrXK-qsg5UpU2vE53klqpRA0bmHFAaPpA.4vRMDAuVvq9ZxIrW?startTime=1623787255000" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>please create a folder named `02_intro-programming` on your computer
<li>download these files within that folder: <a href="/workshop_files/coding-basic-02/shakes.csv" download>data file (shakes.csv)</a>, <a href="/workshop_files/coding-basic-02/lesson.Rmd" download>RMarkdown file (lesson.Rmd)</a>, <a href="/workshop_files/coding-basic-02/02_intro-programming.Rproj" download>R Project file (02_intro-programming.Rproj)</a>, <a href="/workshop_files/coding-basic-02/challenge.Rmd" download>RMarkdown challenge file (challenge.Rmd)</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-basic-02/lesson_key.Rmd" download>RMarkdown lesson file (with answers)</a>
<li><a href="/workshop_files/coding-basic-02/challenge_key.Rmd" download>RMarkdown challenge file (with answers)</a>
</ul>

<hr>

### Week 3: Data Cleaning - Part 1
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/ql2sYMcvOnH5GkrTue5ZNkBCaVoIZfBTVchjovMJHXwMzWmEhvEt0rSQfNBzChy-.S7V-MYQpFWVegtnL" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>please create a folder named `03_data-cleaning` on your computer
<li>download these files within that folder: 
<a href="/workshop_files/coding-basic-03/Study1.csv" download>data file 1 (Study1.csv)</a>, 
<a href="/workshop_files/coding-basic-03/Study1.rda" download>data file 2 (Study1.rda)</a>,
<a href="/workshop_files/coding-basic-03/Study2_Subjects.csv" download>data file 3 (Study2_Subjects.csv)</a>,
<a href="/workshop_files/coding-basic-03/README_Study2.txt" download>Readme file (README_Study2.txt)</a>,
<a href="/workshop_files/coding-basic-03/lesson_orig.Rmd" download>RMarkdown file (lesson_orig.Rmd)</a>, 
<a href="/workshop_files/coding-basic-03/03_data-cleaning.Rproj" download>R Project file (03_data-cleaning.Rproj)</a>, 
<a href="/workshop_files/coding-basic-03/challenge.Rmd" download>RMarkdown challenge file (challenge.Rmd)</a>
</ul>

**After the workshop:**
<ul>
<li>updated version of the lesson file (based on changes made during the workshop): <a href="/workshop_files/coding-basic-03/lesson.Rmd" download>Lesson RMarkdown file (lesson.Rmd)</a>
<li> <a href="/workshop_files/coding-basic-03/lesson_key.Rmd" download>Lesson RMarkdown file (with answers) (lesson_key.Rmd)</a>
<li> <a href="/workshop_files/coding-basic-03/challenge_key.Rmd" download>RMarkdown challenge file (with answers (challenge_key.Rmd)</a>
</ul>

<hr>

### Week 4: Data Cleaning - Part 2 (i.e., Data Manipulation)
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/kCsqybb90-Owiotr9M3W5hO1ay2kcOZvL7F6sGon9EGUi0DzcWe3QAva3D7jxOvS.USkUisXXabanWC8x?startTime=1624996597000" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>please create a folder named `04_data-manipulation` on your computer
<li>download these files within that folder: 
<a href="/workshop_files/coding-basic-04/Study1.csv" download>data file 1 (Study1.csv)</a>, 
<a href="/workshop_files/coding-basic-04/Study1_Followup.csv" download>data file 2 (Study1_Followup.csv)</a>,
<a href="/workshop_files/coding-basic-04/Study2_Subjects.csv" download>data file 3 (Study2_Subjects.csv)</a>,
<a href="/workshop_files/coding-basic-04/Study2_Trials.csv" download>data file 4 (Study2_Trials.csv)</a>,
<a href="/workshop_files/coding-basic-04/README_Study2.txt" download>Readme file (README_Study2.txt)</a>,
<a href="/workshop_files/coding-basic-04/lesson.Rmd" download>RMarkdown file (lesson.Rmd)</a>, 
<a href="/workshop_files/coding-basic-04/04_data-manipulation.Rproj" download>R Project file (04_data-manipulation.Rproj)</a>, 
<a href="/workshop_files/coding-basic-04/Challenge.Rmd" download>RMarkdown challenge file (Challenge.Rmd)</a>
</ul>

**After the workshop:**
<ul>
<li> <a href="/workshop_files/coding-basic-04/lesson_key.Rmd" download>Lesson RMarkdown file (with answers) (lesson_key.Rmd)</a>
<li> <a href="/workshop_files/coding-basic-04/Challenge_Code.Rmd" download>RMarkdown challenge file (with answers; Challenge_Code.Rmd)</a>
</ul>

<hr>

### Week 5: Correlations and basic plotting
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/b0KRaF4Xoi_oK80K_MBFXlDbPUVkIfvWwU4w_cGVyBXabJOVebqbGERGofie4Wee.rsF1U3-ibmTr3Hoi?startTime=1625601330000" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>please create a folder named `05_corr-viz` on your computer
<li>download these files within that folder: 
<a href="/workshop_files/coding-basic-05/lesson.Rmd" download>RMarkdown file</a>, 
<a href="/workshop_files/coding-basic-05/05_corr-viz.Rproj" download>R Project file</a>, 
<a href="/workshop_files/coding-basic-05/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-basic-05/lesson_key.Rmd" download>Lesson RMarkdown file (with answers)</a>
<li><a href="/workshop_files/coding-basic-05/challenge_key.Rmd" download>RMarkdown challenge file (with answers)</a>
</ul>

<hr>

### Week 6: Intro to Regression/Linear Models
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/WiszYKG2W8ryz9XakckFSXhU4o7KhebDo6ZNH2FUPEDHPqU5YUfF_o3Zyf-LVnTg.8usAG8BERltQ2oIq?startTime=1626206131000" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>please create a folder named `06_intro-reg` on your computer
<li>download these files within that folder: 
<a href="/workshop_files/coding-basic-06/lm-lesson.Rmd" download>RMarkdown file</a>, 
<a href="/workshop_files/coding-basic-06/06_intro-reg.Rproj" download>R Project file</a>, 
<a href="/workshop_files/coding-basic-06/lm-challenge.Rmd" download>RMarkdown challenge file</a>
</ul>
**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-basic-06/lm-intro.pdf" download>Workshop slides</a>
<li><a href="/workshop_files/coding-basic-06/lm-lesson_key.Rmd" download>Lesson RMarkdown file (with answers)</a>
<li><a href="/workshop_files/coding-basic-06/lm-challenge_key.Rmd" download>RMarkdown challenge file (with answers)</a>
</ul>

