---
title: "Coding (advanced)"
description: Data analysis workshops for those more familiar with coding principles and/or the R language.
weight: 2
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On this page, you will find resources associated with each session in the advanced-track coding workshop (<a href="https://columbiauniversity.zoom.us/j/96821508904?pwd=U25kdlpienRheFlyMmhKaU9JOFF1Zz09" target="_blank">zoom link</a>, pw: sipps2021).
<br><br>
A few days before each session, please check this page to make sure you've downloaded any necessary files in advance (if needed). After each session, the page will be updated with links to the corresponding zoom recording, as well as any additional materials/answer keys/etc. that were referenced during the workshop.
<hr>

### Week 1: Refresher of regression and moderation (frequentist)
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/IP1_-EPWLHypgEt_krGjQVl5AvQzMh0YREqO460fACXVAYk-A2-t9ECSxK7eQNMl.PUsxRULkO2eFmvAH" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>make sure you have both R and RStudio downloaded on your machine; if you don't, check out [this page](https://cu-psych-computing.github.io/cu-psych-comp-tutorial/tutorials/r-core/1-programming/lessonpart0/#working-with-rstudio-1){target="_blank"} for guidance
</ul>
<br>
**Workshop materials:**
<ul>
<li>R packages used today: `tidyverse` (contains `ggplot2`, `dplyr`, and others); `car`
<li><a href="/workshop_files/coding-adv-01/lm-intro.pdf" download>intro to regression slides</a>
<li><a href="/workshop_files/coding-adv-01/lm-lesson.Rmd" download>RMarkdown lesson file (with notes)</a>
<li><a href="/workshop_files/coding-adv-01/lm-challenge-empty.Rmd" download>RMarkdown challenge file</a> / <a href="/workshop_files/coding-adv-01/lm-challenge.Rmd" download>answer key</a>
</ul>
<br>
**Note:** Please let us know if you are experiencing any issues downloading R and/or installing packages! We also welcome any and all conceptual questions about linear regression, using the `lm()` function, etc.

<hr>

### Week 2: Refresher of regression and moderation (bayesian)
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/_tCCImF61Hm76nJJUeapi83JvSbXxC839T8W5tLw6Vd8dd16T3FoP14gSlQUVOAK.cTAe10RMrs4ZiESc" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>please download the following packages: `rstanarm`, `tidybayes`, `bayesplot` (plus those we used last week: `tidyverse`, `car`)
<li>also download the following files: <a href="/workshop_files/coding-adv-02/lm-lesson-bayes-orig.Rmd" download>RMarkdown lesson file</a>, <a href="/workshop_files/coding-adv-02/lm-lesson-bayes-orig.html" download>HTML lesson file</a>, <a href="/workshop_files/coding-adv-02/lm-challenge-bayesian-orig.Rmd" download>RMarkdown challenge file</a>
</ul>
**After the workshop:**
<ul>
<li>Final workshop materials:
<ul>
<li><a href="/workshop_files/coding-adv-02/lm-lesson-bayes.Rmd" download>RMarkdown lesson file</a> 
<li><a href="/workshop_files/coding-adv-02/lm-lesson-bayes.html" download>HTML lesson file</a>
<li><a href="/workshop_files/coding-adv-02/lm-challenge-bayesian.Rmd" download>RMarkdown challenge file</a>
<li><a href="/workshop_files/coding-adv-02/lm-challenge-answers-bayesian.Rmd" download>RMarkdown challenge file (with answers)</a>
<li><a href="/workshop_files/coding-adv-02/bayesian_regression_slides.pdf" download>Slides from the workshop</a>
</ul></ul>
<hr>

### Week 3: Review: Data wrangling, regression (continued), Frequentist vs. Bayes
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/3e7KARJzQx8ODrypHmhehBdoK1vMzQNTNpWSMLXbN-Ewe_E0QkeJtgEoIRwrbOlp.HmgUI3uBZ8KhRtT6" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>

**After the workshop:**
<ul>
<li>Final workshop materials:
<ul>
<li><a href="/workshop_files/coding-adv-03/bayes-challenge-2.Rmd" download>RMarkdown challenge file</a> 
<li><a href="/workshop_files/coding-adv-03/bayes-challenge-2.html" download>HTML challenge file</a>
<li><a href="/workshop_files/coding-adv-03/bayes-challenge-2_answers.Rmd" download>RMarkdown challenge file (with answers)</a> 
<li><a href="/workshop_files/coding-adv-03/bayes-challenge-2_answers.html" download>HTML challenge file (with answers)</a>
<li><a href="/workshop_files/coding-adv-03/bayes_review.pptx" download>Slides from the workshop</a>
</ul>
</ul>
<hr>

### Week 4: Cleaning data for multi-level modeling

<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/i2WtugWz4-PY0ohg6eg_cDQ6SkbPczOgjtqEW74nEv_CnosQHTYPFHCv1Y-vvpTC.8vhrEYP3OhV7Nbcd" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>

**Before the workshop:**
<ul>
<li>Please download the following workshop materials into one folder:
<ul>
<li><a href="/workshop_files/coding-adv-04/mlm-cleaning-lesson.Rmd" download>RMarkdown lesson file</a> 
<li><a href="/workshop_files/coding-adv-04/mlm-cleaning-lesson.html" download>RMarkdown lesson html</a>
<li><a href="/workshop_files/coding-adv-04/mlm-cleaning-challenge.Rmd" download>RMarkdown challenge file</a>
<li><a href="/workshop_files/coding-adv-04/mlm-data-cleaning.csv" download>data file (mlm-data-cleaning.csv)</a>
</ul>
</ul>
**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-adv-04/mlm-why-how.pptx" download>Slides from the workshop</a> 
<li><a href="/workshop_files/coding-adv-04/mlm-cleaning-challenge-answers.Rmd" download>RMarkdown challenge file (with answers)</a> 
</ul>

<hr>

### Week 5: Time-course/longitudinal data
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/khyYO6B3RXEx1IhrHvDouMLgNa8RTtUxpS5GfolWM0X1o86rcsYWmsd-dpPTGOAJ._8yXEfwM8EmBJfgg" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>Please download the following workshop materials into one folder:
<ul>
<li><a href="/workshop_files/coding-adv-05/mlm-lesson-longitudinal.Rmd" download>RMarkdown lesson file</a> 
<li><a href="/workshop_files/coding-adv-05/mlm-lesson-longitudinal.html" download>RMarkdown lesson html</a>
<li><a href="/workshop_files/coding-adv-05/mlm-longitudinal-challenge.Rmd" download>RMarkdown challenge file</a>
<li><a href="/workshop_files/coding-adv-05/mlm-longitudinal.pdf" download>workshop slides</a>
</ul>
</ul>
**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-adv-05/mlm-longitudinal-challenge_answers.Rmd" download>RMarkdown challenge file (with answers)</a> 
</ul>

<hr>

### Week 6: Multilevel modeling: experimental data
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/D3bG3g8LlhgkCSsWhKATCEuAZpZL3gVjbxWKaaf8v9gCZZ8KpSf53gzm_OOWuV4C.5mqGh6tlAPvIeRwM" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>Please download the following workshop materials into one folder:
<ul>
<li><a href="/workshop_files/coding-adv-06/mlm_experimental_data_updated.Rmd" download>RMarkdown lesson file</a> 
<li><a href="/workshop_files/coding-adv-06/mlm_experimental_data_updated.html" download>RMarkdown lesson html</a>
<li><a href="/workshop_files/coding-adv-06/mlm_experimental_data_challenge_updated.Rmd" download>RMarkdown challenge file</a>
<li><a href="/workshop_files/coding-adv-06/mlm_experimental_data_challenge_updated.html" download>html challenge file</a>
</ul>
</ul>
**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-adv-06/mlm_experimental_data_challenge_answers.Rmd" download>RMarkdown challenge file (with answers)</a>
<li><a href="/workshop_files/coding-adv-06/mlm_experimental_data_challenge_answers.html" download>html challenge file (with answers)</a>
</ul>
<hr>

### Week 7: Multilevel modeling: within-person change
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/eWF6ZpbuDcdQUkfxxduSnf-45ApmxoJ_oTUKSegKRqfwnokmNhb_YDPKsekaUxtu.Kr8CefbLVSE7uKs4" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>Please download the following workshop materials into one folder:
<ul>
<li><a href="/workshop_files/coding-adv-07/mlm_withinperson.Rmd" download>RMarkdown lesson file</a> 
<li><a href="/workshop_files/coding-adv-07/mlm_withinperson.html" download>RMarkdown lesson html</a>
<li><a href="/workshop_files/coding-adv-07/mlm_withinperson_challenge.Rmd" download>RMarkdown challenge file</a>
</ul>
</ul>
**After the workshop:**
<ul>
<li><a href="/workshop_files/coding-adv-07/mlm_withinperson_challenge_answerkey.Rmd" download>RMarkdown challenge file (with answers)</a> 
<li><a href="/workshop_files/coding-adv-07/mlm_withinperson_challenge_answerkey.html" download>html challenge file (with answers)</a>
</ul>
<hr>

### Week 8: Advanced plotting
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/l6QXC-xsFqGCmiNUbap7sbaUz9zYmN2LUn28SUveDLE8gxEGZI-KOtAXDjf8b6Pw.LAq7ooHlR4SEm56X" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>No downloads necessary. Use [this link](https://monicathieu.shinyapps.io/cu-sipps-ggplot-aes/){target="_blank"} to complete the workshop. (Note that if you would like to save your progress, please enable cookies on your web browser.)
</ul>
**After the workshop:**
<ul>
<li>No additional materials.
</ul>

<hr>

### Week 9: Power
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/E_C_qLdxsxconehCTSn0vMHrhJP8RNqJPhOT97DfWVnKrREnIU5p6DLsrHwH_a2B.bGpE0d02x3zGzI0U" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Before the workshop:**
<ul>
<li>No downloads necessary. Use [this link](https://pbloom.shinyapps.io/power_demo/#section-overview){target="_blank"} to complete the workshop. (Note that if you would like to save your progress, please enable cookies on your web browser.)
</ul>