---
title: "Professional Development / Journal Club"
description: Learn about academic research and related scientific careers, as well as how to digest and think critically about contemporary journal articles.
weight: 3
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On this page, you will find resources associated with the Professional Development/Journal Club workshop series (<a href="https://columbiauniversity.zoom.us/j/98891686245?pwd=dUV3S3Z3dkIydTlHRHBVVzlXTThpZz09" target="_blank">zoom link</a>, pw: sipps2021).
<br><br>
Before each journal club session, check this page for details about which article that will be discussed. After each session in the series, the page will be updated with links to the corresponding zoom recording, as well as any additional materials that were referenced during the workshop.
<hr>

### Week 1: What is a good research question?
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/play/gumQ7Qndeg6zzUoXO-vXCXmMQyCaIou-5TxQkZcWdYkObEJra5Asw5qU-SbiVmdQyRHXZAPDE5sSWLlV.BlwvKVmjOxxSK1WW?_x_zm_rhtaid=956&_x_zm_rtaid=m0Fy0B3ORyCzdEtQHq9yTg.1623432286856.181fed33d69d86fd6199bf0824909b53&autoplay=true&continueMode=true&startTime=1623268902000" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/prof-dev/RQ.pdf" download>workshop slides</a>
<li>[link to collaborative brainstorming Google Doc](https://docs.google.com/document/d/1YYvNTHr-aivhlWWP3c5ms12Pkq-bARNTrwpPr_fvQnE/edit#heading=h.b95kkvcec54s){target="_blank"}
</ul>

<hr>

### Week 2: Careers inside and outside academia
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/3iaeCmjRkUBHITaSp-m0883h47dGeEszlHykuSo6R0T54oWjdj_ib1XUiYHMq_aL.JSKrRLVVlPVyCZ_I" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/prof-dev/Ac_and_non-ac_careers.pptx" download>workshop slides</a>
</ul>

<hr>

### Week 3: Journal club
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/E1vzn-jAW0MHMMYBQIqt_h_UiFheSbbCT2nW0wh7kM3IpoqcQIdOsDtpu0KBJB4_.tmNBBDa__XkpYtDs" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<br>
<ul>
<li>This week's reading: [Variety Wins: Soccer-Playing Robots and Infant Walking (Ossmy et al., 2018)](/workshop_files/prof-dev/VarietyWins.pdf){target="_blank"}
<li><a href="/workshop_files/prof-dev/Journal_Club_Jun_23.pdf" download>journal club slides</a>
</ul>

<hr>

### Week 4: Cultural issues within psychology
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/376owC7zOr7FjwfJdoa6cqX8D_brFF9haqgq3Hju4_5m4EJM6RN-TB5PisQ97LXh.XnLK7hFQpiqCTsb8" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>

<hr>

### Week 5: Journal club
<br>
<b>Note:</b> The journal club was cancelled due to unforeseen circumstances and an informal live Q&A session was held instead. No recording will be posted.
<br><br>
**Planned workshop materials:**
<br>
<ul>
<li>Journal club reading: [People use both heterogeneity and minority representation to evaluate diversity (Abascal et al., 2021)](/workshop_files/prof-dev/HeterogeneityMinorityRepDiversity.pdf){target="_blank"}
</ul>

<hr>

### Week 6: CVs & Resumes
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/play/X-lZTW9BYn17LKFgePc-b8g46A6BuUCYleG3s5Vke9AdXK07szNObMqZmcRBuqYLIXsFaEh-AT22WPJk.T8sLJBtUjdeCzsyZ?continueMode=true&_x_zm_rtaid=p0AT7QdfTL2LSvFUEFI6Dw.1626445844098.c26933b50d6986ddbc5182a2fdfb88c8&_x_zm_rhtaid=956" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/prof-dev/CVsResumes_210409.pdf" download>workshop slides</a>
<li>example CVs: <a href="/workshop_files/prof-dev/CV_AV.pdf" target="_blank">Anna V.</a>, <a href="/workshop_files/prof-dev/CV_CG.pdf" target="_blank">Camille G.</a>
<ul><li>**Important!** Don't think of these CVs as a benchmark for what you need to accomplish to get into graduate school! There is a ton of variability in people's research experiences, both in terms of the opportunities they've had access to and the amount of time they've spent in labs.</li>  
</ul>

<hr>

### Week 7: Journal club
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/8x5wmUgqvnzN-7VWptepEV-Jlys7hSJCZYB4WrcEcPqKGNZEoh4ptQEYkd1zQ9Uk.rQN9L6DXnomjuPat" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<br>
<ul>
<li>This week's reading: [Doubts about double dissociations between short- and long-term memory (Ranganath & Blumenfeld, 2005)](/workshop_files/prof-dev/DoubleDissociations_RanganathBlumenfeld.pdf){target="_blank"}
<li><a href="/workshop_files/prof-dev/SIPPS-jclub_072121.pdf" download>journal club slides</a>
</ul>

<hr>

### Week 8: Science communication
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/Lm9JQWJ4hQ6Q-OaLRqjPTrH-a5Jhb98IdmRisTWLBdh1hpLT3pOgO6oCn44yYXyP._lU1BJDX6UcOKcOb" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<br>
<ul>
<li>[This week's reading](/workshop_files/prof-dev/Sarnecka_WritingWorkshop.pdf){target="_blank"}
<li><a href="/workshop_files/prof-dev/slides_scicomm.pdf" download>Workshop slides</a>
</ul>

<hr>

### Week 9: Research ethics
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/Xzp-ZRIU_aDwnUC5WVV2_BDGetRmfURC7kDUBgVV5u_mWqwFFrqrs3cNh47biF04.KkpNmo_y6MVlpzxR" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<br>
<ul>
<li><a href="/workshop_files/prof-dev/SIPPSEthics.pdf" download>Workshop slides</a>
</ul>
<hr>

### Week 10: SIPPS mini-conference (day 1)
<br>
<div align="center"><a href="https://www.youtube.com/watch?v=dfS5Af1-8uI" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
During this session, SIPPS mentees who have completed independent research projects throughout the summer will present their work via posters and data blitzes.
