---
title: "Research Skills"
description: Acquire valuable skills for conducting psychological research, from conducting literature reviews to developing your research question(s) to sharing your results with peers.
weight: 3
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On this page, you will find resources associated with the Research Skills workshop series (<a href="https://columbiauniversity.zoom.us/j/96435187274?pwd=bnpTdzN4R0lJaDFheDZzVUtGa2EyUT09" target="_blank">zoom link</a>, pw: sipps2021).
<br><br>
After each session in the series, the page will be updated with links to the corresponding zoom recording, as well as any additional materials that were referenced during the workshop.
<hr>

### Week 1: How to make the most of your summer experience (Dr. Valerie Purdie-Greenaway)
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/7skt4Grewof6qv0WAy0IucdAjTF70dqtkSvOPNhoTDep7Z5uHnxdaxCb-QahT5eL.86kl_7PINQcwqkSJ" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/research-skills/SummerExp-VGP.pdf" download>workshop slides</a>
</ul>

<hr>

### Week 2: Literature search & Zotero
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/aTzEDzUtrgNRZxjCqkQrGeyrxN8XL1JeqgqpPCPNoEOkcawLyylfdljhI_pZrC-s.P4IjrQT7qkY_4odZ" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/research-skills/LitSearch-AV.pdf" download>workshop slides</a>
</ul>

<hr>

### Week 3: Pre-registration & OSF
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/yIYyLaOThBrTVL5KojCFXBKhtFTiqTmCVZK5N3WMr_a74WLEgykgENiL0rMAzxTl.mPbhDbcZWc_Wjqx4" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/research-skills/Prereg_OSF/PreReg_OSF_slides.pdf" download>Workshop slides</a>
<li><a href="/workshop_files/research-skills/Prereg_OSF/readMe_preRegWorkshop.docx" download>Activity Readme</a>
<li><a href="/workshop_files/research-skills/Prereg_OSF/modifedAffect.csv" download>Datafile</a>
<li><a href="/workshop_files/research-skills/Prereg_OSF/OSF_Prereg_Template.docx" download>OSF Pre-registration template</a>
</ul>

<hr>

### Week 4: Git (Version control & script sharing)
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/play/ZsMlSXLV6-lGTA9fDx47ISVO8RYBSk_mRod_PCqP9-_aqLy7_ZOXPUTVjeKvqEYelsQWqrUkMzpmNAo.8tFYcKxGzZQoqCrD?_x_zm_rhtaid=599&_x_zm_rtaid=7YEOD9OySHa-fbj5JYIM0A.1625492249119.21bbfa79b54e8b2fcc59869b1cb49e19&autoplay=true&continueMode=true&startTime=1625170245000" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>

**Before the workshop:**
<ul>
<li> Please download <a href="/workshop_files/research-skills/Git_installation_instructions.docx" download>this file (Git installation instructions)</a>, and follow the instructions to install git
<li> Sign up for an account on <a href="http://github.com/">github.com</a>, if you don't have one already.
</ul>

**Final workshop materials:**
<ul>
<li><a href="/workshop_files/research-skills/git.pptx" download>Workshop slides</a>
</ul>
<br>

<hr>

### Week 5: Research project progress update
<br>
This week's session included updates from SIPPS participants and their research projects. No materials or recordings will be posted.

<hr>

### Week 6: Qualtrics
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/tcbdkfhDjHOaFpZW2I0mUdQ1SDmxHyagpOY9OpGYXTV4bmYiVy6s0051o8holjOo.rYvjZxhaoRn7DIOi" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>

<hr>

### Week 7: Community-engaged research
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/-W06nK27gfbe6ka9wdNhFhAlHdVuxvBwwk1A_gd8Nq9DToPvnUX0n1pfZGm2gIP4.MmyV7_7-bodOPW80" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
Prior to this week's workshop, please review the following materials:
<ul>
<li>[A Bridge Between Communities The Detroit Community Academic Urban Research Center SD (video)](https://youtu.be/P64TPPZyhhQ){target="_blank"}
<li>[The Development of a Community-Based Family Asthma Management Intervention for Puerto Rican Children (reading)](/workshop_files/research-skills/CommunityBasedAsthmaInterv.pdf){target="_blank"}
<li>[Community-Based Participatory Research: AMOS Health and Hope (video)](https://youtu.be/vPzz-E-61xc){target="_blank"}
</ul>

<hr>

### Week 8: PsychoPy
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/J-Jk88lveo_ZdrXNYNaRR0dnLu2dVclmh-ESkjpop5Dy_3upKO6Cw8pRllaQeHZv.U_U-3wHLXYWUOKGq" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/research-skills/PsychoPyPresentation.pdf" download>Workshop slides</a>
</ul>

<hr>

### Week 9: Practice presentations
<br>
This week's session included practice presentations from SIPPS participants and their research projects. No materials or recordings will be posted.

<hr>

### Week 10: SIPPS mini-conference (day 2)
<br>
<div align="center"><a href="https://columbiauniversity.zoom.us/rec/share/DfsIqBwwnqTrBcLBo6MgPzvwCvl1LCRT7vYrvjJBhlzfQWy_tyMUh1Vw7caFhsmn.H0RsRob9-cwR5jrn" target="_blank" style="padding-bottom:10px"><button><i class="fas fa-video"></i>&nbsp;&nbsp;&nbsp;View Recording</button></a></div>
<br>
During this session, SIPPS mentees who have completed independent research projects throughout the summer will present their work via posters and data blitzes.