---
title: "Professional Development / Journal Club - 2021"
description: Learn about academic research and related scientific careers, as well as how to digest and think critically about contemporary journal articles.
weight: 3
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

See below for resources associated with the professional development/journal club workshop track from SIPPS 2021. For other workshops from 2021, follow [this link](/workshops2021). For <font color="#D6494A">video recordings of these workshops</font>, follow [this link](https://drive.google.com/drive/folders/1G-9GuXuNjvS7h7skizsMvcHF--Q-ugLQ){target="_blank"}.
<hr>

### Week 1: What is a good research question?
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/2021/prof-dev/RQ.pdf" download>workshop slides</a>
<li>[link to collaborative brainstorming Google Doc](https://docs.google.com/document/d/1YYvNTHr-aivhlWWP3c5ms12Pkq-bARNTrwpPr_fvQnE/edit#heading=h.b95kkvcec54s){target="_blank"}
</ul>

<hr>

### Week 2: Careers inside and outside academia
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/2021/prof-dev/Ac_and_non-ac_careers.pptx" download>workshop slides</a>
</ul>

<hr>

### Week 3: Journal club
<br>
**Workshop materials:**
<br>
<ul>
<li>This week's reading: [Variety Wins: Soccer-Playing Robots and Infant Walking (Ossmy et al., 2018)](/workshop_files/2021/prof-dev/VarietyWins.pdf){target="_blank"}
<li><a href="/workshop_files/2021/prof-dev/Journal_Club_Jun_23.pdf" download>journal club slides</a>
</ul>

<hr>

### Week 4: Cultural issues within psychology
<br>
No additional resources for this workshop.
<hr>

### Week 5: Journal club
<br>
<b>Note:</b> The journal club was cancelled due to unforeseen circumstances and an informal live Q&A session was held instead.
<br><br>
**Planned workshop materials:**
<br>
<ul>
<li>Journal club reading: [People use both heterogeneity and minority representation to evaluate diversity (Abascal et al., 2021)](/workshop_files/2021/prof-dev/HeterogeneityMinorityRepDiversity.pdf){target="_blank"}
</ul>

<hr>

### Week 6: CVs & Resumes
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/2021/prof-dev/CVsResumes_210409.pdf" download>workshop slides</a>
<li>example CVs: <a href="/workshop_files/2021/prof-dev/CV_AV.pdf" target="_blank">Anna V.</a>, <a href="/workshop_files/2021/prof-dev/CV_CG.pdf" target="_blank">Camille G.</a>
<ul><li>**Important!** Don't think of these CVs as a benchmark for what you need to accomplish to get into graduate school! There is a ton of variability in people's research experiences, both in terms of the opportunities they've had access to and the amount of time they've spent in labs.</li>  
</ul>

<hr>

### Week 7: Journal club
<br>
**Workshop materials:**
<br>
<ul>
<li>This week's reading: [Doubts about double dissociations between short- and long-term memory (Ranganath & Blumenfeld, 2005)](/workshop_files/2021/prof-dev/DoubleDissociations_RanganathBlumenfeld.pdf){target="_blank"}
<li><a href="/workshop_files/2021/prof-dev/SIPPS-jclub_072121.pdf" download>journal club slides</a>
</ul>

<hr>

### Week 8: Science communication
<br>
**Workshop materials:**
<br>
<ul>
<li>[This week's reading](/workshop_files/2021/prof-dev/Sarnecka_WritingWorkshop.pdf){target="_blank"}
<li><a href="/workshop_files/2021/prof-dev/slides_scicomm.pdf" download>Workshop slides</a>
</ul>

<hr>

### Week 9: Research ethics
<br>
**Workshop materials:**
<br>
<ul>
<li><a href="/workshop_files/2021/prof-dev/SIPPSEthics.pdf" download>Workshop slides</a>
</ul>
<hr>

### Week 10: SIPPS mini-conference (day 1)
<br>
During this session, SIPPS mentees who have completed independent research projects throughout the summer presented their work via posters and data blitzes.
