---
title: "Research Skills - 2021"
description: Acquire valuable skills for conducting psychological research, from conducting literature reviews to developing your research question(s) to sharing your results with peers.
weight: 3
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

See below for resources associated with the research skills workshop series from SIPPS 2021. For other workshops from 2021, follow [this link](/workshops2021).

For <font color="#D6494A">video recordings of these workshops</font>, follow [this link](https://drive.google.com/drive/folders/1G-9GuXuNjvS7h7skizsMvcHF--Q-ugLQ){target="_blank"}.

<hr>

### Week 1: How to make the most of your summer experience (Dr. Valerie Purdie-Greenaway)
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/2021/research-skills/SummerExp-VGP.pdf" download>workshop slides</a>
</ul>

<hr>

### Week 2: Literature search & Zotero
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/2021/research-skills/LitSearch-AV.pdf" download>workshop slides</a>
</ul>

<hr>

### Week 3: Pre-registration & OSF
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/2021/research-skills/Prereg_OSF/PreReg_OSF_slides.pdf" download>Workshop slides</a>
<li><a href="/workshop_files/2021/research-skills/Prereg_OSF/readMe_preRegWorkshop.docx" download>Activity Readme</a>
<li><a href="/workshop_files/2021/research-skills/Prereg_OSF/modifedAffect.csv" download>Datafile</a>
<li><a href="/workshop_files/2021/research-skills/Prereg_OSF/OSF_Prereg_Template.docx" download>OSF Pre-registration template</a>
</ul>

<hr>

### Week 4: Git (Version control & script sharing)
<br>
**Before the workshop:**
<ul>
<li> Please download <a href="/workshop_files/2021/research-skills/Git_installation_instructions.docx" download>this file (Git installation instructions)</a>, and follow the instructions to install git
<li> Sign up for an account on <a href="http://github.com/">github.com</a>, if you don't have one already.
</ul>

**Final workshop materials:**
<ul>
<li><a href="/workshop_files/2021/research-skills/git.pptx" download>Workshop slides</a>
</ul>
<br>

<hr>

### Week 5: Research project progress update
<br>
This week's session included updates from SIPPS participants and their research projects. No additional workshop materials.

<hr>

### Week 6: Qualtrics
<br>
No additional workshop materials.

<hr>

### Week 7: Community-engaged research
<br>
Prior to this week's workshop, please review the following materials:
<ul>
<li>[A Bridge Between Communities The Detroit Community Academic Urban Research Center SD (video)](https://youtu.be/P64TPPZyhhQ){target="_blank"}
<li>[The Development of a Community-Based Family Asthma Management Intervention for Puerto Rican Children (reading)](/workshop_files/2021/research-skills/CommunityBasedAsthmaInterv.pdf){target="_blank"}
<li>[Community-Based Participatory Research: AMOS Health and Hope (video)](https://youtu.be/vPzz-E-61xc){target="_blank"}
</ul>

<hr>

### Week 8: PsychoPy
<br>
**Workshop materials:**
<ul>
<li><a href="/workshop_files/2021/research-skills/PsychoPyPresentation.pdf" download>Workshop slides</a>
</ul>

<hr>

### Week 9: Practice presentations
<br>
This week's session included practice presentations from SIPPS participants and their research projects. No additional materials.

<hr>

### Week 10: SIPPS mini-conference (day 2)
<br>
During this session, SIPPS mentees who have completed independent research projects throughout the summer will present their work via posters and data blitzes.