---
title: "Coding (2022)"
description: Learn how to use R to clean, analyze, and visualize your data.
weight: 1
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

See below for resources associated with the coding workshops from SIPPS 2022. For materials from other years and/or workshop series, follow [this link](/workshops).

<hr>

### Week 1: Setting up your R environment
<br>
**Before the workshop:**
<ul>
<li>download these files: <a href="/workshop_files/2022/coding-01/shakes.csv" download>data file</a>, <a href="/workshop_files/2022/coding-01/01_lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-01/01_setup.Rproj" download>R Project file</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-01/01_lessonKey.Rmd" download>RMarkdown file (with answers)</a>
<ul><li>**Note:** If you have trouble knitting your Rmd file, find the code chunk where you load in a set of packages (using the `library()` function), and *remove* the text `eval = False`.</ul>
<li><a href="/workshop_files/2022/coding-01/coding-intro.pdf" download>Introduction to coding slides</a>
</ul>

<hr>

### Week 2: Programming fundamentals

**Before the workshop:**
<ul>
<li>please create a folder named `02_intro-programming` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-02/shakes.csv" download>data file</a>, <a href="/workshop_files/2022/coding-02/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-02/02_intro-programming.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-02/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-02/lesson_key.Rmd" download>RMarkdown file (with answers)</a>
<li><a href="/workshop_files/2022/coding-02/challenge_key.Rmd" download>Challenge file (with answers)</a>
</ul>

<hr>

### Week 3: Data cleaning, pt. 1

**Before the workshop:**
<ul>
<li>please create a folder named `03_data-cleaning` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-03/Study1.csv" download>Study 1 data file (csv)</a>, <a href="/workshop_files/2022/coding-03/Study1.rda" download>Study 1 data file (rda)</a>, <a href="/workshop_files/2022/coding-03/Study2_Subjects.csv" download>Study 2 data file</a>, <a href="/workshop_files/2022/coding-03/README_Study2.txt" download>Study 2 README</a>, <a href="/workshop_files/2022/coding-03/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-03/03_data-cleaning.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-03/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-03/lesson_key.Rmd" download>RMarkdown file (with answers)</a>
<li><a href="/workshop_files/2022/coding-03/challenge_key.Rmd" download>Challenge file (with answers)</a>
</ul>

<hr>

### Week 4: Data cleaning, pt. 2 (i.e., Data manipulation)

**Before the workshop:**
<ul>
<li>please create a folder named `04_data-manipulation` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-04/Study1.csv" download>Study 1 data file</a>, <a href="/workshop_files/2022/coding-04/Study1_Followup.csv" download>Study 1 followup data file</a>, <a href="/workshop_files/2022/coding-04/Study2_Subjects.csv" download>Study 2 subjects data file</a>, <a href="/workshop_files/2022/coding-04/Study2_Trials.csv" download>Study 2 trials data file</a>, <a href="/workshop_files/2022/coding-04/README_Study2.txt" download>Study 2 README</a>, <a href="/workshop_files/2022/coding-04/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-04/04_data-manipulation.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-04/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-04/lesson_key.Rmd" download>RMarkdown file (with answers)</a>
<li><a href="/workshop_files/2022/coding-04/challenge_key.Rmd" download>Challenge file (with answers)</a>
</ul>

<hr>

### Week 5: No workshop (4th of July)

<hr>

### Week 6: Correlations and basic visualizations

**Before the workshop:**
<ul>
<li>please create a folder named `05_corr-viz` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-05/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-05/05_corr-viz.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-05/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-05/lesson_key.Rmd" download>RMarkdown file (with answers)</a>
<li><a href="/workshop_files/2022/coding-05/challenge_key.Rmd" download>Challenge file (with answers)</a>
</ul>

<hr>

### Week 7: Introduction to linear models

**Before the workshop:**
<ul>
<li>please create a folder named `06_intro-reg` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-06/lm-lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-06/06_intro-reg.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-06/lm-challenge.Rmd" download>RMarkdown challenge file</a>
<li><a href="/workshop_files/2022/coding-06/lm-intro.pdf" download>linear model overview</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-06/lm-lesson_key.Rmd" download>RMarkdown file (with answers)</a>
<li><a href="/workshop_files/2022/coding-06/lm-challenge_key.Rmd" download>Challenge file (with answers)</a>
</ul>

<hr>

### Week 8: Interactions in linear models 

**Before the workshop:**
<ul>
<li>please create a folder named `07_reg-interactions` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-07/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-07/07_reg-interactions.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-07/challenge.Rmd" download>RMarkdown challenge file</a>
<li><a href="/workshop_files/2022/coding-07/lm-intro-interactions.pdf" download>slides on linear models with interactions</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-07/lesson_key.Rmd" download>RMarkdown file (with answers)</a>
<li><a href="/workshop_files/2022/coding-07/challenge_key.Rmd" download>Challenge file (with answers)</a>
</ul>

<hr>

### Week 9: Visualizing  effects  in linear models 

**Before the workshop:**
<ul>
<li>please create a folder named `08_reg-plotting` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-08/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-08/08_reg-plotting.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-08/challenge.Rmd" download>RMarkdown challenge file</a>, <a href="/workshop_files/2022/coding-08/affect.csv" download>data file ("affect.csv")</a>
</ul>

**After the workshop:**
<ul>
<li><a href="/workshop_files/2022/coding-08/lesson_key.Rmd" download>RMarkdown file (with answers)</a>
<li><a href="/workshop_files/2022/coding-08/challenge_key.Rmd" download>Challenge file (with answers)</a>
</ul>

<hr>

### Week 10: Advanced plotting 

**Before the workshop:**
<ul>
<li>please create a folder named `09_adv-viz` on your computer
<li>download these files within that folder: <a href="/workshop_files/2022/coding-09/lesson.Rmd" download>RMarkdown file</a>, <a href="/workshop_files/2022/coding-09/09_adv-viz.Rproj" download>R Project file</a>, <a href="/workshop_files/2022/coding-09/challenge.Rmd" download>RMarkdown challenge file</a>
</ul>
